- name: Install CloudWatch Agent
  ansible.builtin.dnf:
    name: amazon-cloudwatch-agent
    state: present

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Create CloudWatch Agent config file from template
  ansible.builtin.template:
    src: amazon-cloudwatch-agent.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart CloudWatch Agent

- name: Start and enable CloudWatch Agent
  ansible.builtin.service:
    name: amazon-cloudwatch-agent
    state: started
    enabled: true
